### ISSUE TITLE
rdkit=2019.03.4 is not compatible with 3d sampling

### ISSUE THREAD

**Issue by yryMax** [Shen-Lab/LDM-3DG#5]
Dear Authors,

First of all thanks for your great work and the excellent paper! The research is very clear and well-organized. And I appreciate the effort put into sharing the model and dataset.

I ran into problems when trying to run the script `AE_Geometry_and_Unconditional_Latent_Diffusion/sample3_latent_ddpm_qm9_3d.py` 
The error information is `AttributeError: type object 'ChiralType' has no attribute 'CHI_OCTAHEDRAL'
The reason seems to be that the new attributes you added in the [snippet](https://github.com/Shen-Lab/LDM-3DG/blob/45c3a91a7895fefe38b8ec383f5fd64244c55e03/AE_Geometry_and_Unconditional_Latent_Diffusion/datasets/datasets_utils.py#L23-L25) are not contained in rdkit=2019.03.4 (see below screenshot)
<img width="608" alt="image" src="https://github.com/Shen-Lab/LDM-3DG/assets/77325379/b3cdbf7a-4830-4d6d-aab1-20a27b5555f4">

However, if I set rdkit to the newest version, I have vocab issues when running the evaluation script, same problem as in this [issue](https://github.com/wengong-jin/hgraph2graph/issues/44)

**How do you overcome this issue? which version of rdkit are you using so that evaluation script and 3d sampling script can both function?**
Thanks in advance!

**Comment by yryMax** [comment]
Another issue is that the 2d_to_3d decoder under `/AE_geom_uncond_weights_and_data/job16_decoder_2d_to_3d_spatial_graphs/` **cannot be loaded,**  it gives the following error
<img width="767" alt="image" src="https://github.com/Shen-Lab/LDM-3DG/assets/77325379/90defed9-01ef-4c9f-868f-5812cae0c4ba">

The decoder under folder job19(the gssl decoder) can be successfully loaded

**Comment by yyou1996** [comment]
Hi @yryMax,

In my experiments I indeed use two condo environment for the 2D and 3D decoding (mainly the different version of rdkit). The reason is the borrowed AE for 2D and 3D, are developed in very different period of time and I did not manage to make them work in the same environment (still mainly about rdkit version).

For the model weight, I re-upload a version [here](https://zenodo.org/records/11206459) -- last.ckpt which should work now.
